// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskManagerServer.Infra.Database;

#nullable disable

namespace TaskManagerServer.Infra.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251218092449_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("TaskManagerServer.Lib.Domain.Entities.TaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор записи");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Время создания записи");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasComment("Id пользователя создавшего запись");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата и время удаления записи");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("InProcess")
                        .HasComment("Статус операции");

                    b.Property<int>("TaskTypeId")
                        .HasColumnType("integer")
                        .HasComment("FK на таблицу TaskTypes");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Время последнего изменения записи");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasComment("Id пользователя внесшего последние изменения");

                    b.HasKey("Id");

                    b.HasIndex("TaskTypeId");

                    b.ToTable("TaskEntities", (string)null);
                });

            modelBuilder.Entity("TaskManagerServer.Lib.Domain.Entities.TaskType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор записи");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Время создания записи");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasComment("Id пользователя создавшего запись");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата и время удаления записи");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Название типа");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Время последнего изменения записи");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasComment("Id пользователя внесшего последние изменения");

                    b.HasKey("Id");

                    b.ToTable("TaskTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTimeOffset(new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = -1,
                            Name = "Авто",
                            Updated = new DateTimeOffset(new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            UpdatedBy = -1
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTimeOffset(new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = -1,
                            Name = "Авиа",
                            Updated = new DateTimeOffset(new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            UpdatedBy = -1
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTimeOffset(new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = -1,
                            Name = "ЖД",
                            Updated = new DateTimeOffset(new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            UpdatedBy = -1
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTimeOffset(new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = -1,
                            Name = "ТХ",
                            Updated = new DateTimeOffset(new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            UpdatedBy = -1
                        });
                });

            modelBuilder.Entity("TaskManagerServer.Lib.Domain.Entities.TaskEntity", b =>
                {
                    b.HasOne("TaskManagerServer.Lib.Domain.Entities.TaskType", "TaskType")
                        .WithMany("ShipmentPlans")
                        .HasForeignKey("TaskTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskType");
                });

            modelBuilder.Entity("TaskManagerServer.Lib.Domain.Entities.TaskType", b =>
                {
                    b.Navigation("ShipmentPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
